// Mock Legacy Component (Simulating Angular 15 compiled to Angular Element)
// In production, this would be generated by @angular/elements from an Angular 15 build

export class LegacyDashboardElement extends HTMLElement {
    static get observedAttributes() {
        return ['auth-token', 'current-route'];
    }

    constructor() {
        super();
        this.attachShadow({ mode: 'open' });
    }

    connectedCallback() {
        this.render();
        this._setupEventListeners();
    }

    attributeChangedCallback(name, oldValue, newValue) {
        if (oldValue !== newValue) {
            this.render();
        }
    }

    _setupEventListeners() {
        this.shadowRoot.addEventListener('click', (e) => {
            if (e.target.matches('.legacy-link')) {
                e.preventDefault();
                const route = e.target.getAttribute('href');
                this.dispatchEvent(new CustomEvent('legacy-navigate', {
                    detail: { route },
                    bubbles: true,
                    composed: true
                }));
            }
        });
    }

    render() {
        const token = this.getAttribute('auth-token') || 'No Token';
        const route = this.getAttribute('current-route') || '/';

        this.shadowRoot.innerHTML = `
            <style>
                :host {
                    display: block;
                    border: 2px dashed #eab308;
                    padding: 1rem;
                    border-radius: 0.5rem;
                    background: #fffbeb;
                    color: #333;
                }
                h2 { margin-top: 0; color: #a16207; font-size: 1.2rem; }
                .debug {
                    font-family: monospace;
                    font-size: 0.9rem;
                    background: rgba(0,0,0,0.05);
                    padding: 4px;
                }
                button {
                    background: #a16207;
                    color: white;
                    padding: 4px 8px;
                    border: none;
                    cursor: pointer;
                }
                .legacy-nav { margin-top: 10px; display: flex; gap: 10px; }
                .legacy-link { color: blue; text-decoration: underline; cursor: pointer; }
            </style>
            <h2>Legacy Widget (v15 Simulation)</h2>
            <div class="debug">
                <strong>State:</strong><br>
                Auth Token: ${token.substring(0, 15)}...<br>
                Route Awareness: ${route}
            </div>
            <div class="legacy-nav">
                <span>Internal Nav:</span>
                <a href="/settings" class="legacy-link">Settings</a>
                <a href="/profile" class="legacy-link">Profile</a>
            </div>
            <p style="font-size: 0.8rem; margin-top: 10px; color: #666;">
                (This component runs in isolation. It receives inputs via attributes and outputs via CustomEvents)
            </p>
        `;
    }
}

// Register the custom element
customElements.define('legacy-dashboard', LegacyDashboardElement);
